// ClientApp/Dashboard/src/components/forms/textareas/Textarea.tsx
import React, { forwardRef, useState, useRef } from 'react';
import { cn } from '../../../lib/utils';

export interface TextareaProps extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {
  label?: string;
  description?: string;
  error?: string;
  required?: boolean;
  showCount?: boolean;
  maxLength?: number;
  variant?: 'default' | 'filled' | 'outlined';
  resize?: 'none' | 'vertical' | 'horizontal' | 'both';
  autoResize?: boolean;
}

export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(({
  label,
  description,
  error,
  required = false,
  showCount = false,
  maxLength,
  variant = 'default',
  resize = 'vertical',
  autoResize = false,
  className,
  value,
  defaultValue,
  onChange,
  id,
  rows = 3,
  ...props
}, ref) => {
  const [internalValue, setInternalValue] = useState(defaultValue || value || '');
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const textareaId = id || `textarea-${Math.random().toString(36).substr(2, 9)}`;
  const currentValue = value !== undefined ? value : internalValue;
  const characterCount = String(currentValue).length;
  const isOverLimit = maxLength && characterCount > maxLength;

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newValue = e.target.value;

    if (value === undefined) {
      setInternalValue(newValue);
    }

    if (autoResize && textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }

    onChange?.(e);
  };

  const variants = {
    default: 'border-input bg-background',
    filled: 'border-transparent bg-muted',
    outlined: 'border-input bg-background shadow-sm'
  };

  const resizeClasses = {
    none: 'resize-none',
    vertical: 'resize-y',
    horizontal: 'resize-x',
    both: 'resize'
  };

  return (
    <div className={cn('space-y-2', className)}>
      {label && (
        <label htmlFor={textareaId} className="text-sm font-medium text-foreground flex items-center gap-1">
          {label}
          {required && <span className="text-destructive">*</span>}
        </label>
      )}

      <textarea
        ref={(el) => {
          textareaRef.current = el!;
          if (typeof ref === 'function') {
            ref(el);
          } else if (ref) {
            ref.current = el;
          }
        }}
        id={textareaId}
        value={currentValue}
        onChange={handleChange}
        maxLength={maxLength}
        rows={rows}
        className={cn(
          'flex min-h-[80px] w-full rounded-md border px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 transition-colors',
          variants[variant],
          resizeClasses[resize],
          error && 'border-destructive focus-visible:ring-destructive',
          isOverLimit && 'border-destructive focus-visible:ring-destructive',
          className
        )}
        {...props}
      />

      <div className="flex items-center justify-between">
        <div className="flex-1">
          {description && !error && (
            <p className="text-sm text-muted-foreground">{description}</p>
          )}

          {error && (
            <p className="text-sm text-destructive flex items-center gap-1">
              <span className="w-1 h-1 bg-destructive rounded-full flex-shrink-0" />
              {error}
            </p>
          )}

          {isOverLimit && (
            <p className="text-sm text-destructive flex items-center gap-1">
              <span className="w-1 h-1 bg-destructive rounded-full flex-shrink-0" />
              Character limit exceeded ({characterCount}/{maxLength})
            </p>
          )}
        </div>

        {showCount && maxLength && (
          <div className={cn(
            'text-xs',
            isOverLimit ? 'text-destructive' : 'text-muted-foreground'
          )}>
            {characterCount}/{maxLength}
          </div>
        )}
      </div>
    </div>
  );
});

Textarea.displayName = 'Textarea';

export default Textarea;

// ClientApp/Main/src/app/shared/components/ui/input/textarea.component.ts
import { Component, input, output, signal, computed, forwardRef, inject, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR, ReactiveFormsModule, NgControl } from '@angular/forms';

/**
 * Textarea Component - Shadcn/UI style textarea with enhanced accessibility
 */
@Component({
    selector: 'ui-textarea',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule],
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => TextareaComponent),
            multi: true
        }
    ],
    templateUrl: './textarea.component.html',
    styleUrls: ['./textarea.component.scss']
})
export class TextareaComponent implements ControlValueAccessor {
    @ViewChild('textareaElement') textareaElement!: ElementRef<HTMLTextAreaElement>;

    placeholder = input<string>('');
    disabled = input<boolean>(false);
    readonly = input<boolean>(false);
    rows = input<number>(3);
    variant = input<'default' | 'destructive'>('default');
    textareaId = input<string>('');
    ariaDescribedBy = input<string>('');
    required = input<boolean>(false);
    maxLength = input<number | null>(null);
    minLength = input<number | null>(null);
    resize = input<'none' | 'vertical' | 'horizontal' | 'both'>('vertical');

    textareaChange = output<string>();
    textareaBlur = output<void>();
    textareaFocus = output<void>();
    keyDown = output<KeyboardEvent>();

    private _value = signal<string>('');
    value = computed(() => this._value());
    private ngControl = inject(NgControl, { optional: true });
    private onChange = (value: string) => { };
    private onTouched = () => { };

    isInvalid = computed(() => {
        if (this.ngControl) {
            return this.ngControl.invalid && (this.ngControl.dirty || this.ngControl.touched);
        }
        return false;
    });

    textareaClasses = computed(() => {
        const baseClasses = 'flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 transition-colors';

        const variantClasses = {
            default: '',
            destructive: 'border-destructive focus-visible:ring-destructive'
        };

        const resizeClasses = {
            none: 'resize-none',
            vertical: 'resize-y',
            horizontal: 'resize-x',
            both: 'resize'
        };

        const validationClasses = this.isInvalid() ? 'border-destructive focus-visible:ring-destructive' : '';

        return `${baseClasses} ${variantClasses[this.variant()]} ${resizeClasses[this.resize()]} ${validationClasses}`;
    });

    onInput(event: Event): void {
        const target = event.target as HTMLTextAreaElement;
        const newValue = target.value;
        this._value.set(newValue);
        this.onChange(newValue);
        this.textareaChange.emit(newValue);
    }

    onBlur(): void {
        this.onTouched();
        this.textareaBlur.emit();
    }

    onFocus(): void {
        this.textareaFocus.emit();
    }

    onKeyDown(event: KeyboardEvent): void {
        this.keyDown.emit(event);
    }

    focus(): void {
        if (this.textareaElement) {
            this.textareaElement.nativeElement.focus();
        }
    }

    blur(): void {
        if (this.textareaElement) {
            this.textareaElement.nativeElement.blur();
        }
    }

    // ControlValueAccessor implementation
    writeValue(value: string): void {
        this._value.set(value || '');
    }

    registerOnChange(fn: (value: string) => void): void {
        this.onChange = fn;
    }

    registerOnTouched(fn: () => void): void {
        this.onTouched = fn;
    }

    setDisabledState(_isDisabled: boolean): void {
        // Handled by disabled input
    }
}

<textarea #textareaElement [placeholder]="placeholder()" [disabled]="disabled()" [readonly]="readonly()" [rows]="rows()"
    [class]="textareaClasses()" [value]="value()" [id]="textareaId()" [attr.aria-describedby]="ariaDescribedBy()"
    [attr.aria-invalid]="isInvalid()" [attr.aria-required]="required()" [attr.maxlength]="maxLength()"
    [attr.minlength]="minLength()" (input)="onInput($event)" (blur)="onBlur()" (focus)="onFocus()"
    (keydown)="onKeyDown($event)"></textarea>
