// ClientApp/Main/src/app/layout/components/header/header.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatMenuModule } from '@angular/material/menu';
import { MatBadgeModule } from '@angular/material/badge';
import { TranslateModule } from '@ngx-translate/core';
import { ThemeService } from '../../../core/services/theme.service';
import { LayoutService } from '../../../core/services/layout.service';
import { NotificationService } from '../../../core/services/notification.service';
import { Notification } from '../../../core/models/notification.model';

@Component({
    selector: 'app-header',
    standalone: true,
    imports: [CommonModule, MatTooltipModule, TranslateModule, MatMenuModule, MatBadgeModule],
    templateUrl: './header.component.html',
    styleUrl: './header.component.scss'
})
export class HeaderComponent implements OnInit {
    themeService = inject(ThemeService);
    layoutService = inject(LayoutService);
    notificationService = inject(NotificationService);

    isSearchOpen = false;
    currentLang = 'en-US';

    notifications$ = this.notificationService.notifications$;
    unreadCount$ = this.notificationService.unreadCount$;

    ngOnInit() {
        // Language functionality removed - using static English text
    }

    toggleSearch() {
        this.isSearchOpen = !this.isSearchOpen;
    }

    switchLanguage(lang: string) {
        // Language switching removed - using static English text
        localStorage.setItem('language', lang); // Persist if not already handled

        // Optional: Direction change logic
        if (lang.startsWith('ar')) {
            document.documentElement.setAttribute('dir', 'rtl');
            document.documentElement.lang = 'ar';
        } else {
            document.documentElement.setAttribute('dir', 'ltr');
            document.documentElement.lang = 'en';
        }
    }

    setThemeMode(mode: 'light' | 'dark' | 'system') {
        this.themeService.setThemeMode(mode);
    }

    getThemeMode(): 'light' | 'dark' | 'system' {
        return this.themeService.getThemeMode();
    }

    getThemeIcon(): string {
        const mode = this.getThemeMode();
        switch (mode) {
            case 'light':
                return 'fa-sun';
            case 'dark':
                return 'fa-moon';
            case 'system':
                return 'fa-desktop';
            default:
                return 'fa-moon';
        }
    }

    getThemeTooltip(): string {
        const mode = this.getThemeMode();
        const resolvedTheme = this.themeService.isDark() ? 'dark' : 'light';
        
        switch (mode) {
            case 'light':
                return 'Theme: Light';
            case 'dark':
                return 'Theme: Dark';
            case 'system':
                return `Theme: System (${resolvedTheme})`;
            default:
                return 'Theme';
        }
    }

    handleNotificationClick(note: Notification) {
        if (!note.isRead) {
            this.notificationService.markAsRead(note.id).subscribe({
                next: (result) => {
                    if (!result.succeeded) {
                        console.error('Failed to mark notification as read:', result.errors);
                    }
                },
                error: (error) => {
                    console.error('Error marking notification as read:', error);
                }
            });
        }
        if (note.targetUrl) {
            // Navigate if targetUrl exists
            // window.location.href = note.targetUrl; // or router.navigate
        }
    }

    markAllRead() {
        this.notificationService.markAllAsRead().subscribe({
            next: (result) => {
                if (!result.succeeded) {
                    console.error('Failed to mark all notifications as read:', result.errors);
                }
            },
            error: (error) => {
                console.error('Error marking all notifications as read:', error);
            }
        });
    }
}


<div
    class="h-14 mica-effect metallic-border flex items-center justify-between px-2 sm:px-4 md:px-6 transition-all duration-500">
    <div class="flex items-center gap-2 sm:gap-3">
        <div
            class="w-10 h-10 bg-primary rounded-full flex items-center justify-center cursor-pointer hover:opacity-90 transition-opacity flex-shrink-0">
            <span class="text-white font-black text-2xl tracking-tighter italic">f</span>
        </div>

        <!-- Mobile Search Icon -->
        <div class="w-10 h-10 bg-secondary rounded-full flex md:hidden items-center justify-center cursor-pointer hover:bg-black/10 dark:hover:bg-white/10 transition-colors flex-shrink-0"
            (click)="toggleSearch()">
            <i class="fa-solid fa-search text-foreground"></i>
        </div>

        <!-- Mobile Search Input Overlay -->
        <div *ngIf="isSearchOpen"
            class="absolute top-0 left-0 w-full h-14 bg-card flex items-center px-4 z-50 md:hidden animate-fade-in shadow-md">
            <i class="fa-solid fa-arrow-left text-xl text-muted-foreground mr-4 cursor-pointer"
                (click)="toggleSearch()"></i>
            <input type="text" placeholder="Search Community Car" class="fb-input w-full"
                autoFocus>
        </div>

        <!-- Desktop Search Bar -->
        <div class="relative hidden md:block group">
            <i
                class="fa-solid fa-search absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground z-10 group-focus-within:text-primary transition-colors"></i>
            <input type="text" placeholder="Search Community Car"
                class="fb-input pl-10 w-[240px] lg:w-[280px] xl:w-[320px] transition-all focus:w-[360px] focus:pl-4 focus:ring-primary/20 focus:border-primary/50">
        </div>
    </div>

    <nav class="flex items-center h-full hidden md:flex gap-1 lg:gap-4 xl:gap-8 flex-1 justify-center max-w-2xl px-4">
        <div class="relative h-full flex-1 flex items-center justify-center cursor-pointer text-primary transition-all duration-200 hover:bg-secondary/50 rounded-lg my-1 group nav-glow active"
            matTooltip="Home">
            <i class="fa-solid fa-house text-2xl group-active:scale-95 transition-transform"></i>
        </div>
        <div class="relative h-full flex-1 flex items-center justify-center cursor-pointer text-muted-foreground hover:bg-secondary rounded-lg my-1 transition-all duration-200 group nav-glow"
            matTooltip="Friends">
            <i class="fa-solid fa-user-group text-2xl group-active:scale-95 transition-transform"></i>
        </div>
        <div class="relative h-full flex-1 flex items-center justify-center cursor-pointer text-muted-foreground hover:bg-secondary rounded-lg my-1 transition-all duration-200 group nav-glow"
            matTooltip="Video">
            <div class="relative group-active:scale-95 transition-transform">
                <i class="fa-solid fa-tv text-2xl group-hover:scale-110 transition-transform"></i>
                <span class="notification-badge -top-1.5 -right-2">9+</span>
            </div>
        </div>
        <div class="relative h-full flex-1 flex items-center justify-center cursor-pointer text-muted-foreground hover:bg-secondary rounded-lg my-1 transition-all duration-200 group nav-glow"
            matTooltip="Marketplace">
            <i class="fa-solid fa-store text-2xl group-active:scale-95 transition-transform"></i>
        </div>
        <div class="relative h-full flex-1 flex items-center justify-center cursor-pointer text-muted-foreground hover:bg-secondary rounded-lg my-1 transition-all duration-200 group nav-glow"
            matTooltip="Groups">
            <i class="fa-solid fa-users text-2xl group-active:scale-95 transition-transform"></i>
        </div>
    </nav>

    <div class="flex items-center gap-2 sm:gap-3 flex-shrink-0">
        <!-- Language Switcher -->
        <button class="fb-icon-btn active:scale-95 touch-manipulation" [matMenuTriggerFor]="langMenu"
            matTooltip="Language">
            <i class="fa-solid fa-globe text-xl"></i>
        </button>
        <mat-menu #langMenu="matMenu" class="custom-mat-menu">
            <button mat-menu-item (click)="switchLanguage('en-US')" [class.bg-secondary]="currentLang === 'en-US'">
                <span class="mr-2">🇺🇸</span> English
            </button>
            <button mat-menu-item (click)="switchLanguage('ar-EG')" [class.bg-secondary]="currentLang === 'ar-EG'">
                <span class="mr-2">🇪🇬</span> العربية
            </button>
        </mat-menu>

        <!-- Theme Switcher -->
        <button class="fb-icon-btn active:scale-95 touch-manipulation group" [matMenuTriggerFor]="themeMenu"
            [matTooltip]="getThemeTooltip()">
            <i class="fa-solid text-xl theme-toggle-icon transition-all duration-500"
                [ngClass]="{
                    'fa-sun is-dark': getThemeMode() === 'light',
                    'fa-moon is-light': getThemeMode() === 'dark',
                    'fa-desktop': getThemeMode() === 'system'
                }">
            </i>
        </button>
        <mat-menu #themeMenu="matMenu" class="custom-mat-menu">
            <button mat-menu-item (click)="setThemeMode('light')" 
                [class.bg-secondary]="getThemeMode() === '
            </button>
            <button mat-menu-item (click)="setThemeMode('dark')" [class.bg-secondary]="getThemeMode() === 'dark'">
                <i class="fa-solid fa-moon mr-2"></i> Dark
            </button>
            <button mat-menu-item (click)="setThemeMode('system')" [class.bg-secondary]="getThemeMode() === 'system'">
                <i class="fa-solid fa-desktop mr-2"></i> System
            </button>
        </mat-menu>

        <!-- Menu Button (Mobile Only) -->
        <button class="fb-icon-btn active:scale-95 touch-manipulation lg:hidden" matTooltip="Menu"
            (click)="layoutService.toggleMobileMenu()">
            <i class="fa-solid fa-bars text-xl"></i>
        </button>
        <button class="fb-icon-btn relative active:scale-95 touch-manipulation group" matTooltip="Messenger">
            <i class="fa-brands fa-facebook-messenger text-xl group-hover:scale-110 transition-transform"></i>
            <span class="notification-badge -top-1 -right-1 scale-75 origin-top-right">3</span>
        </button>

        <!-- Notifications -->
        <button class="fb-icon-btn relative active:scale-95 touch-manipulation group"
            [matMenuTriggerFor]="notificationMenu"
            matTooltip="Notifications">
            <i class="fa-solid fa-bell text-xl group-hover:rotate-12 transition-transform"
                [class.text-primary]="(unreadCount$ | async)! > 0"></i>
            <span *ngIf="(unreadCount$ | async)! > 0" class="notification-badge">
                {{ (unreadCount$ | async)! > 99 ? '99+' : (unreadCount$ | async) }}
            </span>
        </button>

        <div class="w-10 h-10 rounded-xl bg-secondary/80 mica-effect flex items-center justify-center cursor-pointer hover:border-primary/30 transition-all active:scale-90 ml-1 shadow-sm border border-white/5"
            matTooltip="Account">
            <div class="w-full h-full flex items-center justify-center text-primary font-black italic text-sm">JD</div>
        </div>
    </div>

    <mat-menu #notificationMenu="matMenu" class="notification-menu w-80 sm:w-96">
        <ng-template matMenuContent>
            <div class="px-4 py-3 border-b flex items-center justify-between" (click)="$event.stopPropagation()">
                <h3 class="font-bold text-lg">Notifications</h3>
                <button class="text-xs text-primary hover:underline" (click)="markAllRead()">Mark all as read</button>
            </div>
            <div class="max-h-[70vh] overflow-y-auto">
                <ng-container *ngIf="(notifications$ | async) as notifications">
                    <div *ngIf="notifications.length === 0" class="p-8 text-center text-muted-foreground">
                        <i class="fa-regular fa-bell-slash text-4xl mb-2 opacity-50"></i>
                        <p>No notifications yet</p>
                    </div>

                    <a mat-menu-item *ngFor="let note of notifications"
                        class="!h-auto !py-3 !px-4 border-b last:border-0 hover:bg-secondary/50 transition-colors no-underline block"
                        [ngClass]="{
                            'bg-blue-50': !note.isRead && !themeService.isDark(),
                            'bg-blue-900/10': !note.isRead && themeService.isDark()
                        }" (click)="handleNotificationClick(note)">
                        <span class="flex items-start gap-3 w-full text-left">
                            <span
                                class="w-10 h-10 rounded-full bg-secondary flex-shrink-0 overflow-hidden relative block">
                                <img *ngIf="note.sourceUserAvatar; else defaultAvatar" [src]="note.sourceUserAvatar"
                                    class="w-full h-full object-cover" />
                                <ng-template #defaultAvatar>
                                    <i
                                        class="fa-solid fa-user absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-gray-500"></i>
                                </ng-template>
                                <span *ngIf="!note.isRead"
                                    class="absolute top-0 right-0 w-3 h-3 bg-blue-500 rounded-full border-2 border-card"></span>
                            </span>
                            <span class="flex-1 min-w-0 flex flex-col items-start">
                                <span
                                    class="text-sm font-medium leading-tight mb-1 truncate-2-lines line-clamp-2 whitespace-normal text-left block">
                                    {{ note.message }}
                                </span>
                                <span class="text-xs text-muted-foreground">{{ note.createdAt | date:'short' }}</span>
                            </span>
                        </span>
                    </a>
                </ng-container>
            </div>
        </ng-template>
    </mat-menu>
</div>

// ClientApp/Dashboard/src/components/layout/Header.tsx
import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { cn } from '@/lib/utils';
import { motion, AnimatePresence } from 'framer-motion';
import { useTranslation } from 'react-i18next';
import {
    Search,
    Bell,
    Sun,
    Moon,
    Laptop,
    Languages,
    CheckCircle2,
    AlertCircle,
    Info,
    X
} from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import { useTheme } from '../../contexts/ThemeContext';
import { notificationService } from '../../services/notificationService';
import type { Notification } from '../../services/notificationService';

interface HeaderProps {
    onSearchClick?: () => void;
}

export const Header: React.FC<HeaderProps> = ({ onSearchClick }) => {
    const { t, i18n } = useTranslation();
    const navigate = useNavigate();
    const { user } = useAuth();
    const { theme, setTheme, resolvedTheme } = useTheme();

    // Notifications state
    const [showNotifications, setShowNotifications] = useState(false);
    const [notifications, setNotifications] = useState<Notification[]>([]);
    const [unreadCount, setUnreadCount] = useState(0);
    const notificationRef = useRef<HTMLDivElement>(null);

    // Language state
    const [showLangMenu, setShowLangMenu] = useState(false);
    const langRef = useRef<HTMLDivElement>(null);

    // Theme state
    const [showThemeMenu, setShowThemeMenu] = useState(false);
    const themeRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const fetchNotifications = async () => {
            try {
                const res = await notificationService.getNotifications();
                if (res.succeeded && res.data) {
                    setNotifications(res.data);
                    setUnreadCount(res.data.filter(n => !n.isRead).length);
                }
            } catch (err) {
                console.error('Failed to fetch notifications:', err);
            }
        };

        if (user) {
            fetchNotifications();
            const interval = setInterval(fetchNotifications, 60000); // Poll every minute
            return () => clearInterval(interval);
        }
    }, [user]);

    // Handle clicks outside dropdowns
    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (notificationRef.current && !notificationRef.current.contains(event.target as Node)) {
                setShowNotifications(false);
            }
            if (langRef.current && !langRef.current.contains(event.target as Node)) {
                setShowLangMenu(false);
            }
            if (themeRef.current && !themeRef.current.contains(event.target as Node)) {
                setShowThemeMenu(false);
            }
        };

        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, []);

    const handleMarkAsRead = async (id: string) => {
        try {
            await notificationService.markAsRead(id);
            setNotifications(prev => prev.map(n => n.id === id ? { ...n, isRead: true } : n));
            setUnreadCount(prev => Math.max(0, prev - 1));
        } catch (err) {
            console.error('Failed to mark notification as read:', err);
        }
    };

    const toggleLanguage = (lang: string) => {
        i18n.changeLanguage(lang);
        setShowLangMenu(false);
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    };

    const userRole = user?.roles?.includes('Admin') ? 'Administrator' : 'User';

    const getNotificationIcon = (type: string) => {
        switch (type) {
            case 'Success': return <CheckCircle2 className="w-4 h-4 text-emerald-500" />;
            case 'Warning': return <AlertCircle className="w-4 h-4 text-orange-500" />;
            case 'Error': return <X className="w-4 h-4 text-red-500" />;
            default: return <Info className="w-4 h-4 text-blue-500" />;
        }
    };

    return (
        <header className="h-16 flex items-center justify-between px-6 border-b border-border/50 bg-background/60 backdrop-blur-xl sticky top-0 z-50">
            <div className="flex-1 max-w-xl">
                <div className="relative group">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground transition-colors group-focus-within:text-primary" />
                    <input
                        type="text"
                        placeholder={t('search_anything')}
                        className="w-full bg-muted/50 border border-transparent focus:border-primary/20 focus:bg-background h-10 pl-10 pr-4 rounded-lg outline-none transition-all"
                        onClick={onSearchClick}
                    />
                    <div className="absolute right-3 top-1/2 -translate-y-1/2 hidden md:flex items-center gap-1">
                        <kbd className="px-1.5 py-0.5 rounded border border-border bg-background text-[10px] font-bold text-muted-foreground">⌘</kbd>
                        <kbd className="px-1.5 py-0.5 rounded border border-border bg-background text-[10px] font-bold text-muted-foreground">K</kbd>
                    </div>
                </div>
            </div>

            <div className="flex items-center gap-2 sm:gap-4">
                {/* Theme Toggle */}
                <div className="relative" ref={themeRef}>
                    <button
                        onClick={() => setShowThemeMenu(!showThemeMenu)}
                        className="p-2 rounded-full hover:bg-muted transition-colors text-muted-foreground"
                        title="Toggle theme"
                    >
                        {resolvedTheme === 'dark' ? <Moon className="w-5 h-5" /> : <Sun className="w-5 h-5" />}
                    </button>
                    <AnimatePresence>
                        {showThemeMenu && (
                            <motion.div
                                initial={{ opacity: 0, y: 10, scale: 0.95 }}
                                animate={{ opacity: 1, y: 0, scale: 1 }}
                                exit={{ opacity: 0, y: 10, scale: 0.95 }}
                                className="absolute right-0 mt-2 w-36 bg-card border border-border rounded-2xl shadow-2xl p-2 z-50"
                            >
                                {[
                                    { id: 'light', icon: Sun, label: 'Light' },
                                    { id: 'dark', icon: Moon, label: 'Dark' },
                                    { id: 'system', icon: Laptop, label: 'System' }
                                ].map((item) => (
                                    <button
                                        key={item.id}
                                        onClick={() => { setTheme(item.id as any); setShowThemeMenu(false); }}
                                        className={cn(
                                            "w-full flex items-center gap-2 px-3 py-2 rounded-xl text-sm font-medium transition-colors hover:bg-muted",
                                            theme === item.id && "bg-primary/10 text-primary"
                                        )}
                                    >
                                        <item.icon className="w-4 h-4" />
                                        {item.label}
                                    </button>
                                ))}
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>

                {/* Language Switcher */}
                <div className="relative" ref={langRef}>
                    <button
                        onClick={() => setShowLangMenu(!showLangMenu)}
                        className="p-2 rounded-full hover:bg-muted transition-colors text-muted-foreground"
                        title="Switch language"
                    >
                        <Languages className="w-5 h-5" />
                    </button>
                    <AnimatePresence>
                        {showLangMenu && (
                            <motion.div
                                initial={{ opacity: 0, y: 10, scale: 0.95 }}
                                animate={{ opacity: 1, y: 0, scale: 1 }}
                                exit={{ opacity: 0, y: 10, scale: 0.95 }}
                                className="absolute right-0 mt-2 w-36 bg-card border border-border rounded-2xl shadow-2xl p-2 z-50"
                            >
                                {[
                                    { id: 'en-US', label: 'English', flag: '🇺🇸' },
                                    { id: 'ar-SA', label: 'العربية', flag: '🇸🇦' }
                                ].map((lang) => (
                                    <button
                                        key={lang.id}
                                        onClick={() => toggleLanguage(lang.id)}
                                        className={cn(
                                            "w-full flex items-center gap-2 px-3 py-2 rounded-xl text-sm font-medium transition-colors hover:bg-muted",
                                            i18n.language === lang.id && "bg-primary/10 text-primary"
                                        )}
                                    >
                                        <span className="text-base">{lang.flag}</span>
                                        {lang.label}
                                    </button>
                                ))}
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>

                {/* Notifications */}
                <div className="relative" ref={notificationRef}>
                    <button
                        onClick={() => setShowNotifications(!showNotifications)}
                        className="p-2 rounded-full hover:bg-muted relative transition-colors text-muted-foreground"
                    >
                        <Bell className="w-5 h-5" />
                        {unreadCount > 0 && (
                            <span className="absolute top-1.5 right-1.5 w-4 h-4 bg-primary text-white text-[10px] font-black rounded-full flex items-center justify-center border-2 border-background animate-pulse">
                                {unreadCount}
                            </span>
                        )}
                    </button>
                    <AnimatePresence>
                        {showNotifications && (
                            <motion.div
                                initial={{ opacity: 0, y: 10, scale: 0.95 }}
                                animate={{ opacity: 1, y: 0, scale: 1 }}
                                exit={{ opacity: 0, y: 10, scale: 0.95 }}
                                className="absolute right-0 mt-2 w-80 sm:w-96 bg-card border border-border rounded-3xl shadow-2xl overflow-hidden z-50"
                            >
                                <div className="p-4 border-b border-border bg-muted/30 flex justify-between items-center">
                                    <h4 className="font-black text-sm uppercase tracking-widest">{t('notifications')}</h4>
                                    {unreadCount > 0 && <span className="text-[10px] font-bold bg-primary/10 text-primary px-2 py-0.5 rounded-full">{unreadCount} New</span>}
                                </div>
                                <div className="max-h-[70vh] overflow-y-auto custom-scrollbar">
                                    {notifications.length > 0 ? (
                                        notifications.map((n) => (
                                            <div
                                                key={n.id}
                                                onClick={() => !n.isRead && handleMarkAsRead(n.id)}
                                                className={cn(
                                                    "p-4 border-b border-border/50 cursor-pointer transition-colors hover:bg-muted/50 flex gap-4 ring-inset",
                                                    !n.isRead && "bg-primary/5"
                                                )}
                                            >
                                                <div className="mt-1">{getNotificationIcon(n.type)}</div>
                                                <div className="flex-1 min-w-0">
                                                    <p className="text-xs font-black mb-0.5">{n.title}</p>
                                                    <p className="text-[11px] text-muted-foreground font-medium leading-normal line-clamp-2">{n.message}</p>
                                                    <p className="text-[9px] text-primary/60 font-black mt-2 uppercase tracking-tight">{new Date(n.createdAt).toLocaleString()}</p>
                                                </div>
                                                {!n.isRead && <div className="w-2 h-2 rounded-full bg-primary mt-1.5 shrink-0" />}
                                            </div>
                                        ))
                                    ) : (
                                        <div className="p-8 text-center">
                                            <div className="w-12 h-12 rounded-full bg-muted mx-auto mb-4 flex items-center justify-center text-muted-foreground">
                                                <Bell className="w-6 h-6" />
                                            </div>
                                            <p className="text-sm font-bold text-muted-foreground">All caught up!</p>
                                            <p className="text-xs text-muted-foreground/60 mt-1">No new notifications.</p>
                                        </div>
                                    )}
                                </div>
                                <button className="w-full p-3 text-[10px] font-black uppercase text-center hover:bg-muted transition-colors text-primary tracking-widest bg-muted/10">
                                    View All Notifications
                                </button>
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>

                <div className="h-8 w-px bg-border mx-1" />

                {/* User Menu */}
                <div className="flex items-center gap-3 cursor-pointer pl-1 group" onClick={() => navigate('/settings')}>
                    <div className="text-right hidden sm:block">
                        <div className="text-sm font-semibold group-hover:text-primary transition-colors">{user?.firstName} {user?.lastName}</div>
                        <div className="text-[10px] font-black text-muted-foreground uppercase bg-muted px-1.5 py-0.5 rounded leading-none mt-1">{userRole}</div>
                    </div>
                    <div className="w-10 h-10 rounded-full bg-primary/10 border border-primary/20 flex items-center justify-center font-bold text-primary overflow-hidden group-hover:border-primary/50 transition-all group-hover:scale-105 shadow-lg shadow-primary/5">
                        {user?.profileImageUrl ? (
                            <img src={user.profileImageUrl} alt="Avatar" className="w-full h-full object-cover" />
                        ) : (
                            <span className="text-sm font-black tracking-tighter">{user?.firstName?.[0]}{user?.lastName?.[0]}</span>
                        )}
                    </div>
                </div>
            </div>
        </header>
    );
};
