// ClientApp/Dashboard/src/components/loading/SkeletonScreen.tsx
interface SkeletonProps {
  type?: 'text' | 'card' | 'list' | 'circle' | 'rectangle';
  lines?: number[];
  size?: number;
  width?: number;
  height?: number;
  className?: string;
}

const SkeletonLine = ({ width = '100%' }: { width?: string | number }) => (
  <div
    className="h-4 bg-gradient-to-r from-gray-200 via-gray-300 to-gray-200 bg-[length:200%_100%] animate-loading rounded"
    style={{ width: typeof width === 'number' ? `${width}%` : width }}
  />
);

const SkeletonText = ({ lines = [100, 90, 95] }: { lines?: number[] }) => (
  <div className="space-y-3">
    {lines.map((width, index) => (
      <SkeletonLine key={index} width={width} />
    ))}
  </div>
);

const SkeletonCard = () => (
  <div className="border border-gray-200 rounded-lg overflow-hidden">
    <div className="w-full h-48 bg-gradient-to-r from-gray-200 via-gray-300 to-gray-200 bg-[length:200%_100%] animate-loading" />
    <div className="p-4 space-y-3">
      <SkeletonLine width="75%" />
      <SkeletonLine width="100%" />
      <SkeletonLine width="85%" />
    </div>
  </div>
);

const SkeletonList = () => (
  <div className="space-y-4">
    {[1, 2, 3, 4, 5].map((item) => (
      <div key={item} className="flex items-center space-x-4">
        <div className="w-12 h-12 rounded-full bg-gradient-to-r from-gray-200 via-gray-300 to-gray-200 bg-[length:200%_100%] animate-loading" />
        <div className="flex-1 space-y-2">
          <SkeletonLine width="25%" />
          <SkeletonLine width="100%" />
        </div>
      </div>
    ))}
  </div>
);

const SkeletonCircle = ({ size = 48 }: { size?: number }) => (
  <div
    className="rounded-full bg-gradient-to-r from-gray-200 via-gray-300 to-gray-200 bg-[length:200%_100%] animate-loading"
    style={{ width: size, height: size }}
  />
);

const SkeletonRectangle = ({ width = 200, height = 100 }: { width?: number; height?: number }) => (
  <div
    className="rounded bg-gradient-to-r from-gray-200 via-gray-300 to-gray-200 bg-[length:200%_100%] animate-loading"
    style={{ width, height }}
  />
);

export const SkeletonScreen = ({
  type = 'text',
  lines,
  size,
  width,
  height,
  className = ''
}: SkeletonProps) => {
  return (
    <div className={className} role="status" aria-label="Loading content">
      {type === 'text' && <SkeletonText lines={lines} />}
      {type === 'card' && <SkeletonCard />}
      {type === 'list' && <SkeletonList />}
      {type === 'circle' && <SkeletonCircle size={size} />}
      {type === 'rectangle' && <SkeletonRectangle width={width} height={height} />}
    </div>
  );
};

// ClientApp/Main/src/app/shared/components/loading/skeleton-screen.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-skeleton-screen',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [class]="containerClass" role="status" aria-label="Loading content">
      <div *ngIf="type === 'text'" class="space-y-3">
        <div *ngFor="let line of lines" class="skeleton-line" [style.width.%]="line"></div>
      </div>
      
      <div *ngIf="type === 'card'" class="skeleton-card">
        <div class="skeleton-image"></div>
        <div class="p-4 space-y-3">
          <div class="skeleton-line w-3/4"></div>
          <div class="skeleton-line w-full"></div>
          <div class="skeleton-line w-5/6"></div>
        </div>
      </div>
      
      <div *ngIf="type === 'list'" class="space-y-4">
        <div *ngFor="let item of [1,2,3,4,5]" class="flex items-center space-x-4">
          <div class="skeleton-avatar"></div>
          <div class="flex-1 space-y-2">
            <div class="skeleton-line w-1/4"></div>
            <div class="skeleton-line w-full"></div>
          </div>
        </div>
      </div>
      
      <div *ngIf="type === 'circle'" class="skeleton-circle" [style.width.px]="size" [style.height.px]="size"></div>
      
      <div *ngIf="type === 'rectangle'" class="skeleton-rectangle" [style.width.px]="width" [style.height.px]="height"></div>
    </div>
  `,
  styles: [`
    .skeleton-line {
      height: 1rem;
      background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
      background-size: 200% 100%;
      animation: loading 1.5s ease-in-out infinite;
      border-radius: 0.25rem;
    }
    
    .skeleton-card {
      border: 1px solid #e5e7eb;
      border-radius: 0.5rem;
      overflow: hidden;
    }
    
    .skeleton-image {
      width: 100%;
      height: 12rem;
      background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
      background-size: 200% 100%;
      animation: loading 1.5s ease-in-out infinite;
    }
    
    .skeleton-avatar {
      width: 3rem;
      height: 3rem;
      border-radius: 50%;
      background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
      background-size: 200% 100%;
      animation: loading 1.5s ease-in-out infinite;
    }
    
    .skeleton-circle {
      border-radius: 50%;
      background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
      background-size: 200% 100%;
      animation: loading 1.5s ease-in-out infinite;
    }
    
    .skeleton-rectangle {
      border-radius: 0.25rem;
      background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
      background-size: 200% 100%;
      animation: loading 1.5s ease-in-out infinite;
    }
    
    @keyframes loading {
      0% { background-position: 200% 0; }
      100% { background-position: -200% 0; }
    }
  `]
})
export class SkeletonScreenComponent {
  @Input() type: 'text' | 'card' | 'list' | 'circle' | 'rectangle' = 'text';
  @Input() lines: number[] = [100, 90, 95];
  @Input() size: number = 48;
  @Input() width: number = 200;
  @Input() height: number = 100;
  @Input() containerClass: string = '';
}
