// ClientApp/Dashboard/src/components/shared/EmptyState.tsx
import React from 'react';
import { motion } from 'framer-motion';
import type { LucideIcon } from 'lucide-react';

export interface EmptyStateProps {
  icon: LucideIcon;
  title: string;
  description: string;
  actionLabel?: string;
  onAction?: () => void;
  className?: string;
  iconClassName?: string;
  showAction?: boolean;
}

export const EmptyState: React.FC<EmptyStateProps> = ({
  icon: Icon,
  title,
  description,
  actionLabel = 'Get Started',
  onAction,
  className = '',
  iconClassName = '',
  showAction = true
}) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className={`flex flex-col items-center justify-center py-12 px-6 text-center ${className}`}
    >
      <div className={`w-16 h-16 mb-6 text-muted-foreground/50 ${iconClassName}`}>
        <Icon className="w-full h-full" />
      </div>
      
      <h3 className="text-xl font-semibold text-foreground mb-2">
        {title}
      </h3>
      
      <p className="text-muted-foreground mb-6 max-w-md leading-relaxed">
        {description}
      </p>
      
      {showAction && onAction && (
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={onAction}
          className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors font-medium"
        >
          {actionLabel}
        </motion.button>
      )}
    </motion.div>
  );
};

export default EmptyState;

// ClientApp/Main/src/app/shared/components/empty-state/empty-state.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-empty-state',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './empty-state.component.html',

})
export class EmptyStateComponent {
    @Input() icon = 'fa-inbox';
    @Input() message = 'No items found';
    @Input() description = 'Try adjusting your filters or search terms';
    @Input() actionText?: string;
    @Input() actionIcon?: string;
}

<div
    class="flex flex-col items-center justify-center p-8 text-center bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 min-h-[300px]">
    <div class="mb-4 text-gray-400 dark:text-gray-500">
        <i [class]="'fa-solid text-4xl ' + icon"></i>
    </div>
    <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-2">{{ message }}</h3>
    <p class="text-sm text-gray-500 dark:text-gray-400 max-w-sm mb-6">{{ description }}</p>
    <button *ngIf="actionText"
        class="inline-flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground hover:bg-primary/90 rounded-md text-sm font-medium transition-colors">
        <i *ngIf="actionIcon" [class]="'fa-solid ' + actionIcon"></i>
        {{ actionText }}
    </button>
</div>
